# Pull ros-noetic full desktop 
FROM osrf/ros:noetic-desktop-full
SHELL ["/bin/bash", "-c"]

ENV ROSINSTALL_PREFIX=https://raw.githubusercontent.com/cram2/cram/devel
ENV CRAM_ROSINSTALL_FILE="${ROSINSTALL_PREFIX}/cram-20.04-http.rosinstall"
ENV JUPYTER_ROSINSTALL_FILE="${ROSINSTALL_PREFIX}/jupyter/common-lisp-jupyter.rosinstall"

# ------
RUN echo ""
RUN echo "--- Set up ROS environment variables ---"
RUN echo ""
RUN source /opt/ros/noetic/setup.bash
ENV ROS_PACKAGE_PATH=/home/workspace/ros/src:/opt/ros/noetic/share:/opt/ros/noetic/stacks
ENV CMAKE_PREFIX_PATH=/home/workspace/ros/devel:/opt/ros/noetic
ENV PATH=/opt/ros/noetic/bin:$PATH
ENV ROS_ROOT=/opt/ros/noetic/share/ros
ENV PYTHONPATH=/home/workspace/ros/devel/lib/python3/dist-packages:/opt/ros/noetic/lib/python3/dist-packages
ENV PATH=/root/.local/bin:$PATH
RUN rosdep update # using as root is not intended, it works though.

# ------
RUN echo ""
RUN echo "--- Install ROS tools and dependencies ---"
RUN echo ""
RUN apt-get update && apt-get upgrade -y 
RUN apt-get install -y dialog curl git python3-dev python3-pip python3-catkin-tools python3-rosdep \
python3-rosinstall python3-rosinstall-generator python3-wstool build-essential ros-noetic-roslisp-repl

# ------
RUN echo ""
RUN echo "--- Set up Catkin Workspace ---"
RUN echo ""
RUN mkdir -p /home/workspace/ros/src 
WORKDIR /home/workspace/ros
RUN catkin init
WORKDIR /home/workspace/ros/src
RUN wstool init
RUN wstool merge $CRAM_ROSINSTALL_FILE
RUN wstool update
RUN rosdep install -y --ignore-src --from-paths ./ -r
WORKDIR /home/workspace/ros/
RUN catkin build

# ------
RUN echo ""
RUN echo "--- Install Juypterlab ---"
RUN echo ""
RUN pip install jupyterlab
RUN pip install --upgrade zipp
WORKDIR /home/workspace/ros/src
RUN catkin_create_pkg jupyter
WORKDIR /home/workspace/ros/src/jupyter
RUN wstool init 
RUN wstool merge $JUPYTER_ROSINSTALL_FILE
RUN wstool update
RUN rosdep install -y --ignore-src --from-paths ./ -r
WORKDIR /home/workspace/ros/
RUN catkin build
ENV ROSLISP_PACKAGE_DIRECTORIES=/home/workspace/ros/devel/share/common-lisp
RUN /usr/bin/sbcl --load /home/workspace/ros/src/cram/jupyter/sbcl-jupyter-kernel-installer.lisp

# ------
RUN apt-get install net-tools
WORKDIR /home/lectures
RUN echo ""
RUN echo "--- Set entry point ---"
RUN echo ""
WORKDIR /home
COPY cram_launch.sh /cram_launch.sh
RUN chmod +x /cram_launch.sh
ENTRYPOINT ["/cram_launch.sh"]
