# Create docker file of A lightweight kinematics simulation of IAI's PR2 robot
# 1. Pull ros-robot base
# 2. Install py pkg for giskard
# 3. Create workspace for for Giskard (changing directories as required)
# 4. configuring docker or port 

# Pull ros-robot base
FROM osrf/ros:noetic-desktop-full
SHELL ["/bin/bash", "-c"]

# source ROS
RUN source /opt/ros/noetic/setup.bash
RUN echo $CMAKE_PREFIX_PATH

#Explicitly source ros
ENV ROS_PACKAGE_PATH=/home/ros/iai_pr2_sim_ws/src:/opt/ros/noetic/share:/opt/ros/noetic/stacks
ENV CMAKE_PREFIX_PATH=/home/ros/iai_pr2_sim_ws/devel:/opt/ros/noetic
RUN echo $ROS_PACKAGE_PATH
RUN echo $CMAKE_PREFIX_PATH

#installing python3 catkin tools
RUN sudo apt-get update && apt-get upgrade -y 
RUN sudo apt-get update --fix-missing
RUN sudo apt-get install -y git m4 python python3-pip wget
RUN sudo apt-get install -y python3-catkin-pkg-modules python3-rospkg-modules 
RUN sudo pip3 install -U catkin_tools
RUN sudo apt-get install -y python3-rosdep python3-rosinstall python3-rosinstall-generator python3-wstool build-essential
RUN sudo apt-get install -y python3-empy
RUN sudo pip3 install scipy
RUN sudo pip3 install urdf_parser_py

# Setting up workspace
WORKDIR /home/ros/iai_pr2_sim_ws
RUN echo $PWD
RUN catkin init
WORKDIR src
RUN echo $PWD
RUN wstool init
RUN wstool merge https://raw.githubusercontent.com/code-iai/iai_pr2/master/iai_pr2_sim/rosinstall/catkin-melodic.rosinstall
RUN wstool update
RUN rosdep install -y --ignore-src --from-paths iai_pr2/
WORKDIR ..
RUN echo $PWD

# Explicitly catkin build
ENV PYTHONPATH=/opt/ros/noetic/lib/python3/dist-packages
RUN echo $PYTHONPATH
RUN catkin build -DPYTHON_EXECUTABLE=/usr/bin/python3

#Configure container startup     
COPY ipr2_launch.sh /ipr2_launch.sh
ENTRYPOINT ["/ipr2_launch.sh"]


